language: ruby

rvm:
  - 2.2

cache:
  bundler: true

script:
  - bundle exec rubocop -D
  - bundle exec rspec spec/models
  - bundle exec rspec spec/requests
  - bundle exec rspec
  - bundle exec brakeman -zA
