language: ruby

rvm:
  - 2.2

env:
  global:
    - CODECLIMATE_REPO_TOKEN=ca17436bff753caad1e0ae63a5985c74fcb90ad03ee162e93d7098582af75aed

cache:
  bundler: true

script:
  - bundle exec rubocop -D
  - bundle exec rspec
  - bundle exec brakeman -zA
  - bundle exec codeclimate-test-reporter
