# This is the shared Rubocop configuration for SUSE projects. It is maintained
# at https://github.com/SUSE/style-guides/blob/master/rubocop-suse.yml
#
# The configuration is tested and used with the Rubocop version used by Hound
# (http://hound-ci.com).
#
# We use the default Hound config as a baseline:
#
#   https://raw.githubusercontent.com/thoughtbot/hound/master/config/style_guides/ruby.yml
#
# This file contains the rules with derive from this.
